# Generated by Django 4.2.19 on 2025-05-17 06:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_camera_user_alter_alert_id_alter_camera_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detections/'),
        ),
        migrations.CreateModel(
            name='AlertTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
                ('last_alert_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.camera')),
            ],
            options={
                'unique_together': {('camera', 'object_type')},
            },
        ),
    ]
